version: "2"
services:
    nacos:
        image: nacos/nacos-server:latest
        container_name: nacos-standalone-mysql-ip
        environment:
            - PREFER_HOST_MODE=ip
            - MODE=standalone
            - SPRING_DATASOURCE_PLATFORM=mysql
            - MYSQL_SERVICE_HOST=127.0.0.1
            - MYSQL_SERVICE_DB_NAME=nacos_dev
            - MYSQL_SERVICE_PORT=3306
            - MYSQL_SERVICE_USER=nacos
            - MYSQL_SERVICE_PASSWORD=Nacos_dev.2020
            #- NACOS-NAMESPACE=nacos-mysql   #指定nacos中的命名空间
        volumes:
            - ./standalone-logs/:/home/nacos/logs
            - ./example/init.d/custom.properties:/home/nacos/init.d/custom.properties
        ports:
            - "8848:8848"
            - "9555:9555"
        restart: on-failure
        networks:
            nacos_net:
                ipv4_address: 172.16.3.10
networks:
    nacos_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.3.0/24
